# Generated by Django 3.1.1 on 2020-09-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confederacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confederancy_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=25)),
                ('district_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=25)),
                ('village_name', models.CharField(max_length=25)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fijiApi.districts')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confederancy_code', models.CharField(max_length=25)),
                ('province_name', models.CharField(max_length=25)),
                ('confederancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fijiApi.confederacy')),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fijiApi.provinces'),
        ),
    ]
