# Generated by Django 3.1.1 on 2020-09-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fijiApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='province',
        ),
        migrations.RemoveField(
            model_name='provinces',
            name='confederancy',
        ),
        migrations.RemoveField(
            model_name='villages',
            name='district',
        ),
    ]
