# Generated by Django 3.1.1 on 2020-09-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fijiApi', '0002_auto_20200903_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.provinces'),
        ),
        migrations.AddField(
            model_name='provinces',
            name='confederancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.confederacy'),
        ),
        migrations.AddField(
            model_name='villages',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.districts'),
        ),
    ]
