# Generated by Django 3.1.1 on 2020-09-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fijiApi', '0003_auto_20200903_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='confederancy',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.confederacy'),
        ),
    ]
