# Generated by Django 3.1.1 on 2020-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fijiApi', '0004_auto_20200903_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='villages',
            name='acknowledgement',
            field=models.TextField(default=''),
        ),
    ]
