# Generated by Django 3.1.1 on 2020-09-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fijiApi', '0005_villages_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='confederancy',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.confederacy'),
        ),
        migrations.AddField(
            model_name='villages',
            name='confederancy',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fijiApi.confederacy'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='fijiApi.provinces'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='confederancy',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province', to='fijiApi.confederacy'),
        ),
        migrations.AlterField(
            model_name='villages',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village', to='fijiApi.districts'),
        ),
    ]
